spring:
  application:
    name: member-command
  data:
    mongodb:
      uri: mongodb://localhost:27017/member_command
  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 8080

management:
  otlp:
    metrics:
      export:
        enabled: false

otel:
  sdk:
    disabled: true

bits:
  ddd:
    observability:
      logback:
        enabled: false

