spring:
  application:
    name: member-command
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  mongodb:
    uri: mongodb://localhost:27017/member_command

server:
  port: 8080

management:
  otlp:
    metrics:
      export:
        enabled: false

otel:
  sdk:
    disabled: true

bits:
  ddd:
    observability:
      logback:
        enabled: false

